#!/usr/bin/env bash

if [ $# -eq 1 ]
        then
          source Other/E_env/bin/activate
          python3 Other/xtcp.py $1
        elif [ $# -gt 1 ]
        then
          echo "Error: This program can only take a maximum of 1 command"
        else
          source Other/E_env/bin/activate
          python3 Other/xtcp.py 4567
fi

