#!/usr/bin/env bash

source Common/Other/Fish_env/bin/activate
cd Common
python3 -m unittest

echo integration test 3
cd ../../3
./xboard < ./Tests/1-in.json | diff - Tests/1-out.json
./xboard < ./Tests/2-in.json | diff - Tests/2-out.json
./xboard < ./Tests/3-in.json | diff - Tests/3-out.json


echo integration test 4
cd ../4
./xstate < ./Tests/1-in.json | diff - Tests/1-out.json
./xstate < ./Tests/2-in.json | diff - Tests/2-out.json
./xstate < ./Tests/3-in.json | diff - Tests/3-out.json


echo integration test 5
cd ../5
./xtree < ./Tests/1-in.json | diff - Tests/1-out.json
./xtree < ./Tests/2-in.json | diff - Tests/2-out.json
./xtree < ./Tests/3-in.json | diff - Tests/3-out.json

echo integration test 6
cd ../6
./xstrategy < ./Tests/1-in.json | diff - Tests/1-out.json
./xstrategy < ./Tests/2-in.json | diff - Tests/2-out.json
./xstrategy < ./Tests/3-in.json | diff - Tests/3-out.json
./xstrategy < ./Tests/4-in.json | diff - Tests/4-out.json
./xstrategy < ./Tests/5-in.json | diff - Tests/5-out.json

echo integration test 8
cd ../8
./xref < ./Tests/1-in.json | diff - Tests/1-out.json
./xref < ./Tests/2-in.json | diff - Tests/2-out.json
./xref < ./Tests/3-in.json | diff - Tests/3-out.json