#!/usr/bin/env python3

from json import dumps, loads
from sys import stdin, stdout, path

# somewhat janky way to be able to import board.py from Common/
path.insert(0, "../Fish/Common")
from jsoninterpreter import json_to_state, convert_dw_to_pos
path.insert(0, "../Fish/Player")
import strategy

# Reads in from stdin
infile = stdin.read()

# get json object
jsonobj = loads(infile)

# convert to GameTree node
state = json_to_state(jsonobj[1])
depth = jsonobj[0]

# run choose_action to get the correct move
strat = strategy.MinimaxStrategy(state.turn)
dw_move = strat.choose_action(state, depth)

if dw_move:
# Convert the positions in the move from our double-width to the col, row
    move = (convert_dw_to_pos(dw_move[0]), convert_dw_to_pos(dw_move[1]))
else:
    move = False

# Write to stdout
stdout.write(dumps(move))